//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra.WPApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zebra.WPApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string AppBarDownload {
            get {
                return ResourceManager.GetString("AppBarDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string TilePlaces {
            get {
                return ResourceManager.GetString("TilePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string TileWallet {
            get {
                return ResourceManager.GetString("TileWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s going on.
        /// </summary>
        public static string TileWhatsGoingOn {
            get {
                return ResourceManager.GetString("TileWhatsGoingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TxbCategoriesCategories {
            get {
                return ResourceManager.GetString("TxbCategoriesCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TxbCategoriesSearch {
            get {
                return ResourceManager.GetString("TxbCategoriesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        public static string TxbCategoriesSearchBox {
            get {
                return ResourceManager.GetString("TxbCategoriesSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on a second while we set up your settings and download the places you chosed..
        /// </summary>
        public static string TxbDownloadingInfo {
            get {
                return ResourceManager.GetString("TxbDownloadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporters.
        /// </summary>
        public static string TxbEventReportersReporters {
            get {
                return ResourceManager.GetString("TxbEventReportersReporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in and ready to go..
        /// </summary>
        public static string TxbFacebookLoggedIn {
            get {
                return ResourceManager.GetString("TxbFacebookLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        public static string TxbFacebookLogin {
            get {
                return ResourceManager.GetString("TxbFacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string TxbFindCategory {
            get {
                return ResourceManager.GetString("TxbFindCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND US A PLACE.
        /// </summary>
        public static string TxbFindHeader {
            get {
                return ResourceManager.GetString("TxbFindHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your limit.
        /// </summary>
        public static string TxbFindItemMaxMoney {
            get {
                return ResourceManager.GetString("TxbFindItemMaxMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much are you gonna spend.
        /// </summary>
        public static string TxbFindItemMinMoney {
            get {
                return ResourceManager.GetString("TxbFindItemMinMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use your local currency.
        /// </summary>
        public static string TxbFindItemMinMoneyHint {
            get {
                return ResourceManager.GetString("TxbFindItemMinMoneyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people are there.
        /// </summary>
        public static string TxbFindItemPeople {
            get {
                return ResourceManager.GetString("TxbFindItemPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put a number.
        /// </summary>
        public static string TxbFindItemPeopleHint {
            get {
                return ResourceManager.GetString("TxbFindItemPeopleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string TxbFindOr {
            get {
                return ResourceManager.GetString("TxbFindOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something.
        /// </summary>
        public static string TxbFindSearch {
            get {
                return ResourceManager.GetString("TxbFindSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string TxbFindSearchBoxHint {
            get {
                return ResourceManager.GetString("TxbFindSearchBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &quot;normal&quot; day.
        /// </summary>
        public static string TxbInfoTitle {
            get {
                return ResourceManager.GetString("TxbInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zebritas.
        /// </summary>
        public static string TxbMenu {
            get {
                return ResourceManager.GetString("TxbMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TxbPlaceAddress {
            get {
                return ResourceManager.GetString("TxbPlaceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string TxbPlaceFeatures {
            get {
                return ResourceManager.GetString("TxbPlaceFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this place you can find things or services that go from.
        /// </summary>
        public static string TxbPlacePriceDescription {
            get {
                return ResourceManager.GetString("TxbPlacePriceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string TxbPlacePriceTo {
            get {
                return ResourceManager.GetString("TxbPlacePriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string TxbPlaceRating {
            get {
                return ResourceManager.GetString("TxbPlaceRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string TxbPlaceRelated {
            get {
                return ResourceManager.GetString("TxbPlaceRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by features.
        /// </summary>
        public static string TxbPlaceRelatedByFeatures {
            get {
                return ResourceManager.GetString("TxbPlaceRelatedByFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by prices.
        /// </summary>
        public static string TxbPlaceRelatedByPrice {
            get {
                return ResourceManager.GetString("TxbPlaceRelatedByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one.
        /// </summary>
        public static string TxbReportChoose {
            get {
                return ResourceManager.GetString("TxbReportChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a short descrption.
        /// </summary>
        public static string TxbReportDescription {
            get {
                return ResourceManager.GetString("TxbReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string TxbSettingsDistance {
            get {
                return ResourceManager.GetString("TxbSettingsDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a distance you thinks is near enough for you.
        /// </summary>
        public static string TxbSettingsDistanceDetail {
            get {
                return ResourceManager.GetString("TxbSettingsDistanceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string TxbSettingsFacebook {
            get {
                return ResourceManager.GetString("TxbSettingsFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string TxbSettingsPlace {
            get {
                return ResourceManager.GetString("TxbSettingsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string TxbSettingsPreference {
            get {
                return ResourceManager.GetString("TxbSettingsPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TxbSettingsTitle {
            get {
                return ResourceManager.GetString("TxbSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TxbSubCategoriesAll {
            get {
                return ResourceManager.GetString("TxbSubCategoriesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near.
        /// </summary>
        public static string TxbSubCategoriesNear {
            get {
                return ResourceManager.GetString("TxbSubCategoriesNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string TxbSubCategoriesPopular {
            get {
                return ResourceManager.GetString("TxbSubCategoriesPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string TxbTroublesMap {
            get {
                return ResourceManager.GetString("TxbTroublesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubles.
        /// </summary>
        public static string TxbTroublesTroubles {
            get {
                return ResourceManager.GetString("TxbTroublesTroubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the categories you are most interesed in.
        /// </summary>
        public static string TxbWhatDownload {
            get {
                return ResourceManager.GetString("TxbWhatDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string TxtbAuto {
            get {
                return ResourceManager.GetString("TxtbAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the latest places around you.
        /// </summary>
        public static string TxtbDownloadPlaces {
            get {
                return ResourceManager.GetString("TxtbDownloadPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebritas will check for new places everytime you open the app and have a connection to the Internet. This only takes some seconds and doesn&apos;t affect your data plan dramatically, you&apos;re welcome..
        /// </summary>
        public static string TxtbDownloadPlacesAuto {
            get {
                return ResourceManager.GetString("TxtbDownloadPlacesAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebritas will display the places you choose to download a few moments ago. Don&apos;t worry, you can update this list anytime..
        /// </summary>
        public static string TxtbDownloadPlacesManual {
            get {
                return ResourceManager.GetString("TxtbDownloadPlacesManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string TxtbKilometers {
            get {
                return ResourceManager.GetString("TxtbKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string TxtbMiles {
            get {
                return ResourceManager.GetString("TxtbMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login in Facebook to start using the app..
        /// </summary>
        public static string TxtFacebookNeeded {
            get {
                return ResourceManager.GetString("TxtFacebookNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string TxtFind {
            get {
                return ResourceManager.GetString("TxtFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPS on your device is disabled. Please activate it and return here..
        /// </summary>
        public static string TxtGPSDisabled {
            get {
                return ResourceManager.GetString("TxtGPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy, you&apos;re really far away from civilization! We couldn&apos;t locate you, please try again later..
        /// </summary>
        public static string TxtGPSNoData {
            get {
                return ResourceManager.GetString("TxtGPSNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not connected to the Internet. Verify your WiFi connection or if your data plan is activaded..
        /// </summary>
        public static string TxtInternetConnectionProblem {
            get {
                return ResourceManager.GetString("TxtInternetConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places found near you. Check your application settings to see when you consider a place is near you..
        /// </summary>
        public static string TxtNoNearPlaces {
            get {
                return ResourceManager.GetString("TxtNoNearPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places found for this category.
        /// </summary>
        public static string TxtNoPlaces {
            get {
                return ResourceManager.GetString("TxtNoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find related places for this particular place..
        /// </summary>
        public static string TxtNoPlacesRelated {
            get {
                return ResourceManager.GetString("TxtNoPlacesRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No popular places found. Check your application settings to see what you consider popular..
        /// </summary>
        public static string TxtNoPopularPlaces {
            get {
                return ResourceManager.GetString("TxtNoPopularPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string TxtReport {
            get {
                return ResourceManager.GetString("TxtReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something awful happened to our server, please try again later..
        /// </summary>
        public static string TxtReportFailed {
            get {
                return ResourceManager.GetString("TxtReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already reported something near here. Sorry, we can&apos;t let your report more than once in a closed distance..
        /// </summary>
        public static string TxtReportRepeated {
            get {
                return ResourceManager.GetString("TxtReportRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve succesfully reported a problem, thank you..
        /// </summary>
        public static string TxtReportSucceded {
            get {
                return ResourceManager.GetString("TxtReportSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the thing you want us to search for you..
        /// </summary>
        public static string TxtSearchFailed {
            get {
                return ResourceManager.GetString("TxtSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item from the list..
        /// </summary>
        public static string TxtSelectedItemFailed {
            get {
                return ResourceManager.GetString("TxtSelectedItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string TxtShare {
            get {
                return ResourceManager.GetString("TxtShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  places found.
        /// </summary>
        public static string TxtSubCategoriesPlacesFound {
            get {
                return ResourceManager.GetString("TxtSubCategoriesPlacesFound", resourceCulture);
            }
        }
    }
}
